### ISSUE TITLE
Arrows to small boxes next to big boxes unnecessarily cross the big box

### ISSUE THREAD

**Issue by airhorns** [steveruizok/perfect-arrows#4]
![boxes](https://user-images.githubusercontent.com/158950/92775668-9892da80-f36c-11ea-87b0-21a375e38236.gif)

Maybe this is by design, but I'd kind of expect the arrow to shrink smaller and smaller between the two boxes until it no longer fit before starting on the opposite side of the box. I am working around this right now by making the big box appear on top of the line with a bigger `zIndex`, but it still stinks if there is any bowing or if one wanted to use the control midpoint to position a label or something like that.

I took a look and the issue is related to `getSegmentRoundedRectangleIntersectionPoints` but my geometry fu is not strong enough to immediately see how to fix this. Happy to work on a PR if someone could give me a pointer!

**Comment by steveruizok** [comment]
You’re right, that looks like a bug! There’s an escape hatch when a test doesn’t produce enough intersections because the boxes are too close. It seems to be misfiring or too eager. Let’s see if we can find out what else would cause it to not have enough intersections.

**Comment by olkivan** [comment]
@steveruizok Please take a look at my PR, I've slightly modified the algorithm so the main idea is to find intersection points using a single segment between box1 and box2 center points. Also the triggering condition for an existing fallback algorithm is a simple aabb intersection. It should work perfect with zero pads. I slightly modified your example app as well. You can check the result here(there even much more modified example version than PR modification but the algo is the same): http://95.214.9.220/   I'd appreciate any response. Thanks!

**Comment by steveruizok** [comment]
Hey @olkivan, commented on the PR! Also @airhorns I have a new branch up where I'm working on a better solution for close / overlapping boxes. Would love your thoughts / tweaks! https://github.com/steveruizok/perfect-arrows/tree/feature/box-to-box-1.1

![2020-09-18 at 12 14 16 - Amaranth Sheep copy](https://user-images.githubusercontent.com/23072548/93596348-12504700-f9b1-11ea-8ef4-2b294695b751.gif)

**Comment by airhorns** [comment]
That looks great to me, especially for my use case of putting a label at the control point of the line, moving it outwards like that and giving control over the min distance means I can "ask" the algorithm for space for a label. Super!

**Comment by olkivan** [comment]
@steveruizok could you please also merge the box-to-box-1.1 branch into the master? I'd really like to use this functionality from the npm package.

**Comment by steveruizok** [comment]
Collisions are going to still be tricky, but this issue is much improved from 0.3! https://github.com/steveruizok/perfect-arrows/pull/10

**Comment by airhorns** [comment]
Thanks Steve!!
